// AUTO-GENERATED by scripts/sync-engine-to-edge.mjs — do not edit. Run `npm run sync:edge`.
/**
 * Grid construction, access, and equality helpers.
 *
 * Grids are immutable. Every transform in rule.ts returns a NEW grid rather
 * than mutating, which keeps R(C) a pure function (§11.2: "Pure function
 * R(C) → answer. This is the testable core").
 */

import type { Cell, Grid } from "./types.ts";
import { EMPTY, COLORS, isColor } from "./types.ts";

export function makeGrid(cells: ReadonlyArray<ReadonlyArray<Cell>>): Grid {
  const rows = cells.length;
  if (rows === 0) throw new Error("grid must have at least one row");
  const cols = cells[0]!.length;
  if (cols === 0) throw new Error("grid must have at least one column");
  for (const row of cells) {
    if (row.length !== cols) {
      throw new Error("all rows must have the same length");
    }
  }
  // Defensive copy so the returned grid is genuinely immutable even if the
  // caller mutates their source array afterward.
  return {
    rows,
    cols,
    cells: cells.map((row) => row.slice()),
  };
}

/** Read a cell. Throws on out-of-bounds — callers must pass valid coords; the
 *  rule engine is responsible for clamping/validating selection coords. */
export function cellAt(grid: Grid, row: number, col: number): Cell {
  if (!inBounds(grid, row, col)) {
    throw new Error(`cell (${row},${col}) out of bounds for ${grid.rows}x${grid.cols} grid`);
  }
  return grid.cells[row]![col]!;
}

export function inBounds(grid: Grid, row: number, col: number): boolean {
  return row >= 0 && row < grid.rows && col >= 0 && col < grid.cols;
}

/** Build a mutable working copy of a grid's cells for transforms to fill in. */
export function toMutableCells(grid: Grid): Cell[][] {
  return grid.cells.map((row) => row.slice());
}

/** All-empty cells of the given shape (used as the canvas under "empty as
 *  background" shifts, where vacated positions default to empty). */
export function emptyCells(rows: number, cols: number): Cell[][] {
  return Array.from({ length: rows }, () => Array.from({ length: cols }, () => EMPTY as Cell));
}

export function gridsEqual(a: Grid, b: Grid): boolean {
  if (a.rows !== b.rows || a.cols !== b.cols) return false;
  for (let r = 0; r < a.rows; r++) {
    for (let c = 0; c < a.cols; c++) {
      if (a.cells[r]![c] !== b.cells[r]![c]) return false;
    }
  }
  return true;
}

/**
 * Parse a compact text grid for tests/fixtures. Rows are separated by newlines
 * or "/"; cells by nothing (one char each). Use 'R' 'G' 'B' for colors and
 * '_' or '.' or ' ' for empty.
 *
 *   parseGrid("R_/_G")  ->  [[R, _], [_, G]]
 */
export function parseGrid(text: string): Grid {
  const rows = text
    .trim()
    .split(/[\n/]/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
  const cells: Cell[][] = rows.map((line) =>
    [...line].map((ch) => {
      if (ch === "_" || ch === "." || ch === " ") return EMPTY;
      const up = ch.toUpperCase();
      if ((COLORS as readonly string[]).includes(up)) return up as Cell;
      throw new Error(`unrecognized cell char: ${JSON.stringify(ch)}`);
    }),
  );
  return makeGrid(cells);
}

/** Render a grid back to the compact text form (for test diffs / debugging). */
export function formatGrid(grid: Grid): string {
  return grid.cells.map((row) => row.map((cell) => (isColor(cell) ? cell : ".")).join("")).join("/");
}
