// AUTO-GENERATED by scripts/sync-engine-to-edge.mjs — do not edit. Run `npm run sync:edge`.
/**
 * Deterministic PRNG for the grid clock (DESIGN.md §10: "same fn on phone +
 * server → identical rolling grid").
 *
 * Requirements that drove the choice:
 *   - Pure & deterministic: identical output for identical (seed, tick) on every
 *     platform. NO Math.random, NO time, NO platform crypto API differences.
 *   - Seedable from a string seed + an integer tick.
 *   - Good enough distribution that generated grids look "pleasant"/varied
 *     (§4b). This is NOT a security primitive — the grid is PUBLIC (§9.3); the
 *     PRNG only needs to be deterministic and well-spread, not cryptographic.
 *
 * Implementation: splitmix64-style 64-bit mixing done in BigInt (so it is exact
 * and identical across JS engines), exposed as a small uint/float API.
 */

const MASK64 = (1n << 64n) - 1n;

/** FNV-1a 64-bit hash of a string → BigInt. Used to fold a string seed and the
 *  tick into a single 64-bit state deterministically. */
export function hashSeed(seed: string, tick: number): bigint {
  let h = 0xcbf29ce484222325n; // FNV offset basis
  const prime = 0x100000001b3n;
  const data = `${seed}#${tick}`;
  for (let i = 0; i < data.length; i++) {
    h ^= BigInt(data.charCodeAt(i));
    h = (h * prime) & MASK64;
  }
  return h;
}

/** A stateful deterministic generator. Not cryptographic. */
export class Prng {
  private state: bigint;

  constructor(state: bigint) {
    // Avoid the all-zero state (splitmix handles it fine, but normalize anyway).
    this.state = state & MASK64;
  }

  static fromSeed(seed: string, tick: number): Prng {
    return new Prng(hashSeed(seed, tick));
  }

  /** Next 64-bit value (splitmix64). */
  private next64(): bigint {
    this.state = (this.state + 0x9e3779b97f4a7c15n) & MASK64;
    let z = this.state;
    z = ((z ^ (z >> 30n)) * 0xbf58476d1ce4e5b9n) & MASK64;
    z = ((z ^ (z >> 27n)) * 0x94d049bb133111ebn) & MASK64;
    z = z ^ (z >> 31n);
    return z & MASK64;
  }

  /** Uniform integer in [0, n). n must be a positive safe integer. */
  nextInt(n: number): number {
    if (!Number.isInteger(n) || n <= 0) throw new Error(`nextInt bound must be a positive integer, got ${n}`);
    // Rejection sampling for an unbiased result.
    const bound = BigInt(n);
    const limit = MASK64 - (MASK64 % bound);
    let r: bigint;
    do {
      r = this.next64();
    } while (r > limit);
    return Number(r % bound);
  }

  /** Uniform float in [0, 1). */
  nextFloat(): number {
    // 53 high bits → double in [0,1).
    return Number(this.next64() >> 11n) / 2 ** 53;
  }
}
