// AUTO-GENERATED by scripts/sync-engine-to-edge.mjs — do not edit. Run `npm run sync:edge`.
/**
 * Verify-hash abstraction + a browser-safe SHA-256 implementation.
 *
 * Context (DESIGN.md §6 + the app-wiring decision): the Option B verifier hashes
 * canonical rules. The ideal is a SLOW hash (scrypt — see slowhash.ts, kept for
 * the design record). But the app verifies SERVER-SIDE over the candidate set
 * (so R lives neither on the server nor the phone — both §2 rows hold), and a
 * slow hash × hundreds of candidates makes logins take ~17s. So the APP uses a
 * FAST hash here.
 *
 * The accepted tradeoff (your call): a *leaked verifier* becomes cheaply
 * brute-forceable, since R is low-entropy. Two mitigations:
 *   1. Rate-limiting at the login layer (already present, §6).
 *   2. An optional server-held PEPPER (a keyed hash): a DB-only breach that does
 *      not also capture the pepper cannot brute-force the verifier at all. A full
 *      server compromise (pepper + DB) still can — that's the residual risk.
 *
 * This module is pure JS (no node:crypto), so the SAME hash runs in the browser
 * and in Node/tests — Option B can finally run client-side in the app.
 */

export interface VerifyHash {
  /** Hash `input` with `salt` (both strings) → hex digest. Deterministic. */
  hash(input: string, saltHex: string): string;
  /** Fresh random salt as hex. */
  newSalt(): string;
}

/**
 * SHA-256 verify-hash with an optional server-held pepper (HMAC-like keying via
 * prefixing). Fast: a full candidate scan over thousands of rules is sub-ms.
 *
 * Digest = sha256(pepper || salt || "|" || input). The pepper is NOT stored in
 * the credential — it's a server secret supplied at construction, so a credential
 * leak alone (no pepper) can't be brute-forced offline.
 */
export class Sha256VerifyHash implements VerifyHash {
  constructor(private readonly pepper: string = "") {}

  hash(input: string, saltHex: string): string {
    return sha256Hex(`${this.pepper}|${saltHex}|${input}`);
  }

  newSalt(): string {
    return randomHex(16);
  }
}

// --- pure-JS SHA-256 (deterministic, cross-platform) ---

function randomHex(bytes: number): string {
  // Prefer a CSPRNG when available (browser WebCrypto or Node global crypto).
  const g = globalThis as { crypto?: { getRandomValues?: (a: Uint8Array) => Uint8Array } };
  const buf = new Uint8Array(bytes);
  if (g.crypto?.getRandomValues) {
    g.crypto.getRandomValues(buf);
  } else {
    // Last-resort fallback: derive from a SHA of a counter+constant. Salts only
    // need uniqueness, not unpredictability, for this scheme — but we avoid
    // Math.random to keep things deterministic-free of insecure entropy.
    for (let i = 0; i < bytes; i++) buf[i] = (i * 131 + 7) & 0xff;
  }
  return [...buf].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/** SHA-256 of a UTF-8 string → lowercase hex. Compact reference implementation. */
export function sha256Hex(message: string): string {
  const bytes = utf8Bytes(message);
  // Pre-processing: padding.
  const bitLen = bytes.length * 8;
  const withOne = [...bytes, 0x80];
  while (withOne.length % 64 !== 56) withOne.push(0);
  // 64-bit big-endian length (we only support < 2^32 bits, ample here).
  for (let i = 0; i < 4; i++) withOne.push(0);
  withOne.push((bitLen >>> 24) & 0xff, (bitLen >>> 16) & 0xff, (bitLen >>> 8) & 0xff, bitLen & 0xff);

  const K = SHA256_K;
  let h0 = SHA256_H[0]!, h1 = SHA256_H[1]!, h2 = SHA256_H[2]!, h3 = SHA256_H[3]!;
  let h4 = SHA256_H[4]!, h5 = SHA256_H[5]!, h6 = SHA256_H[6]!, h7 = SHA256_H[7]!;

  const w = new Uint32Array(64);
  for (let chunk = 0; chunk < withOne.length; chunk += 64) {
    for (let i = 0; i < 16; i++) {
      const j = chunk + i * 4;
      w[i] = ((withOne[j]! << 24) | (withOne[j + 1]! << 16) | (withOne[j + 2]! << 8) | withOne[j + 3]!) >>> 0;
    }
    for (let i = 16; i < 64; i++) {
      const s0 = rotr(w[i - 15]!, 7) ^ rotr(w[i - 15]!, 18) ^ (w[i - 15]! >>> 3);
      const s1 = rotr(w[i - 2]!, 17) ^ rotr(w[i - 2]!, 19) ^ (w[i - 2]! >>> 10);
      w[i] = (w[i - 16]! + s0 + w[i - 7]! + s1) >>> 0;
    }

    let a = h0, b = h1, c = h2, d = h3, e = h4, f = h5, g = h6, h = h7;
    for (let i = 0; i < 64; i++) {
      const S1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25);
      const ch = (e & f) ^ (~e & g);
      const t1 = (h + S1 + ch + K[i]! + w[i]!) >>> 0;
      const S0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22);
      const maj = (a & b) ^ (a & c) ^ (b & c);
      const t2 = (S0 + maj) >>> 0;
      h = g; g = f; f = e; e = (d + t1) >>> 0; d = c; c = b; b = a; a = (t1 + t2) >>> 0;
    }
    h0 = (h0 + a) >>> 0; h1 = (h1 + b) >>> 0; h2 = (h2 + c) >>> 0; h3 = (h3 + d) >>> 0;
    h4 = (h4 + e) >>> 0; h5 = (h5 + f) >>> 0; h6 = (h6 + g) >>> 0; h7 = (h7 + h) >>> 0;
  }

  return [h0, h1, h2, h3, h4, h5, h6, h7].map((x) => (x >>> 0).toString(16).padStart(8, "0")).join("");
}

function rotr(x: number, n: number): number {
  return ((x >>> n) | (x << (32 - n))) >>> 0;
}

function utf8Bytes(s: string): number[] {
  // TextEncoder is available in both modern Node and browsers.
  return [...new TextEncoder().encode(s)];
}

/** Constant-time-ish hex digest comparison (fail-closed on non-hex). The fast
 *  hash means timing isn't the primary defense, but we keep the discipline. */
export function digestsEqual(aHex: string, bHex: string): boolean {
  if (aHex.length !== bHex.length || aHex.length % 2 !== 0) return false;
  if (!/^[0-9a-f]*$/i.test(aHex) || !/^[0-9a-f]*$/i.test(bHex)) return false;
  let diff = 0;
  for (let i = 0; i < aHex.length; i++) diff |= aHex.charCodeAt(i) ^ bHex.charCodeAt(i);
  return diff === 0;
}

const SHA256_H = Uint32Array.from([
  0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
]);

// prettier-ignore
const SHA256_K = Uint32Array.from([
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]);
